"""add knowledge_chunks for campaign-knowledge RAG

Revision ID: a1c4e7d90b23
Revises: f5770ad9a28c
Create Date: 2026-07-19 10:00:00.000000

Hand-written (not autogenerated): pgvector's Vector column type and the HNSW
index aren't fully round-tripped by Alembic's model-based autogenerate, so both
are declared explicitly here. Dimensionality (1536) matches the configured
embedding model (OpenAI text-embedding-3-small); changing the embedding model
to a different dimension requires a new migration, not just a config edit.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'a1c4e7d90b23'
down_revision: Union[str, Sequence[str], None] = 'f5770ad9a28c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_EMBEDDING_DIM = 1536


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'knowledge_chunks',
        sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
        sa.Column('doc_title', sa.String(length=255), nullable=False),
        sa.Column('doc_type', sa.String(length=50), nullable=False),
        sa.Column('chunk_text', sa.Text(), nullable=False),
        sa.Column('embedding', Vector(_EMBEDDING_DIM), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_knowledge_chunks_doc_title'), 'knowledge_chunks', ['doc_title'], unique=False)
    # HNSW index for cosine-distance ANN search (matches the <=> operator used
    # by the retriever). Created via raw SQL since the vector opclass isn't
    # expressible through op.create_index's dialect-agnostic API.
    op.execute(
        "CREATE INDEX ix_knowledge_chunks_embedding_hnsw ON knowledge_chunks "
        "USING hnsw (embedding vector_cosine_ops)"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP INDEX IF EXISTS ix_knowledge_chunks_embedding_hnsw")
    op.drop_index(op.f('ix_knowledge_chunks_doc_title'), table_name='knowledge_chunks')
    op.drop_table('knowledge_chunks')
